RIPPLING_DIRECTORY_NAME = "rippling_cli"
OAUTH_TOKEN_FILE_NAME = "oauth_token.json"
CODE_CHALLENGE_METHOD = "S256"
RIPPLING_BASE_URL = "https://app.rippling.com"
RIPPLING_API = "https://app.rippling.com/api"
EXIT_UNKNOWN_EXCEPTION = 1
DEFAULT_CODE_VERIFIER_LENGTH = 43
