RIPPLING_DIRECTORY_NAME = "rippling_cli"
OAUTH_TOKEN_FILE_NAME = "oauth_token.json"
CODE_CHALLENGE_METHOD = "S256"
RIPPLING_BASE_URL = "http://localhost:3000"
RIPPLING_API = "http://localhost:8000"
EXIT_UNKNOWN_EXCEPTION = 1
